### ISSUE TITLE
The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") ...

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-composer#13]
### What steps will reproduce the problem?
composer update
### What's expected?
no errors
### What do you get instead?
$ composer self-update
The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
You are already using composer version 1.1.3 (stable channel).
Skybook-Pro:hello Jeff$ composer update
The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by newscloud** [comment]
I ran into some github commit errors - and then updating composer again once made this go away. It may be a non-issue.

**Comment by cebe** [comment]
see #6
