### ISSUE TITLE
Installer::postInstall is not callable (error on composer install)

### ISSUE THREAD

**Issue by gvanto** [yiisoft/yii2-composer#15]
Example here (readme):
https://github.com/yiisoft/yii2-composer
Shows "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ]

When I attempt to configure this script to update a folder's permissions (frontend/runtime), I get error "Installer::postInstall is not callable"

(noticed there is not method 'postInstall' in class yii2-composer/Installer.php class... )

### What steps will reproduce the problem?
Simply try the example posted in the readme

### What's expected?
Folder's permissions to be updated

### What do you get instead?
Error (see above).

A working example of how to update folder permissions using yii2-composer would be great.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2
| PHP version      | 5.5
| Operating system | Ubuntu 14.04

**Comment by cebe** [comment]
this feature is not released yet. We'll ship a new version of this extension with the next release of the framework I think.

**Comment by gvanto** [comment]
Thanks cebe.

The Installer: setPermissions() does exist - but I keep getting error 'expects array, object received' error - any idea how I can pass an array to this method?

Many thanks

**Comment by cebe** [comment]
your error is about Installer::postInstall not Installer: setPermissions(). To use this feature you have to install the unstable version of yii2-composer:

    composer require 'yiisoft/yii2-composer:~2.0.0@dev'

**Comment by gvanto** [comment]
Yup the setPermissions error is a different error to my original post/issue here. I don't necessarily need postInstall to work I don't think (I don't actually see why I need it at all?), just setPermissions() ... with the correct passed parameters - but that is where I am stuck - how to pass the parameters to it?

**Comment by cebe** [comment]
it is explained in the readme: https://github.com/yiisoft/yii2-composer#usage

**Comment by gvanto** [comment]
Thanks but when I follow example in that link, using this code in composer.json:

`"scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::setPermission"
        ]
    },
    "extra": {
      "yii\\composer\\Installer::setPermission": [
            {
            "backend/runtime": "0777",
            "backend/web/assets": "0777"
            }
        ]  
    }`

I get error:

>  post-install-cmd: yii\composer\Installer::setPermission
> Script yii\composer\Installer::setPermission handling the post-install-cmd event terminated with an exception
> 
> 
>   [ErrorException]
>   Argument 1 passed to yii\composer\Installer::setPermission() must be of the type array, object given, called in
>    phar:///usr/local/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php on line 233 and defined
