### ISSUE TITLE
2.0.7 release?

### ISSUE THREAD

**Issue by angrybrad** [yiisoft/yii2-composer#19]
I realize there's only [one bug fix](https://github.com/yiisoft/yii2-composer/pull/18), but any chance there will be a 2.0.7 release in the not too distant future?

Some services like ServerPilot have the restrict_api setting enabled by default and several people are getting bitten by it. https://github.com/craftcms/cms/issues/2834

**Comment by cebe** [comment]
sure, will tag it this week.

**Comment by schmunk42** [comment]
btw, just as a general versioning thing (now that we have semver :smiley:) - it would be great if patches like this could be released much faster, more often and without a fixed time-cycle - also no big release announcement needed (as long as tests are green and there's CHANGELOG entry).

Even for just one commit/one line - if it's a patch, increment the patch level in a tag and you're good to go.

CC: @samdark

**Comment by samdark** [comment]
Tagging it right now :)

**Comment by samdark** [comment]
Done.

**Comment by angrybrad** [comment]
Thanks much!
