### ISSUE TITLE
Plugin yiisoft/yii2 composer couldnot be initialized class not found : yii\composer\plugin

### ISSUE THREAD

**Issue by VeeraSanthanaLakshmi** [yiisoft/yii2-composer#25]
### What steps will reproduce the problem?
Used Vagrant bento/ubuntu18.04
installed PHP 7.2
installed MySQL 
installed composer package
then comper install or composer update returns this error
### What's expected?
To install the composer packages
### What do you get instead?
throws an error like this
Plugin yiisoft/yii2 composer could not be initialized class not found: yii\composer\plugin
### Additional info
![composererror1](https://user-images.githubusercontent.com/32504855/68463520-d72fa400-0234-11ea-8505-81a393dd8d0c.png)

| Q                | A
| ---------------- | ---
| Yii version       | Yii2
| PHP version      | 7.2
| Operating system | windows 10

**Comment by cebe** [comment]
I have seen such issues with vagrant when using shared folders. Can you show your Vagrantfile?

**Comment by VeeraSanthanaLakshmi** [comment]
Switching vagrant to centos from ubuntu, solved this issue for me. Yes, there may be an issue with shared folders.

**Comment by freeze000** [comment]
I try to install Yii2 with Vagrant on this manual https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md#installing-using-vagrant

In result I have problem:
```
throws an error like this
Plugin yiisoft/yii2 composer could not be initialized class not found: yii\composer\plugin
```

I don't solve this problem.

**Comment by samdark** [comment]
That seems to be vagrant-specific problem. Please report to yii2-app-advanced repository.

**Comment by cebe** [comment]
Seems there is a bug in Virtualbox, see https://github.com/yiisoft/yii2-app-advanced/issues/448 for more details.

**Comment by senguttuvang** [comment]
> I have seen such issues with vagrant when using shared folders. Can you show your Vagrantfile?
> Switching the driver of shared folder solved the issue for me.

What was your original setting for the driver and what did you change?

**Comment by cebe** [comment]
original driver that has this issue is `vboxfs`, switching to `nfs` solves it, but NFS setup is more complicated than simple vboxfs, see https://github.com/yiisoft/yii2-app-advanced/issues/448#issuecomment-555917793 for more details.

**Comment by javier-acierto** [comment]
Hi, we had the same problem, because I shared a vm made with virtual box 6, and my team was using a below version, they upgraded virtual box, and the problem was solved.

**Comment by RCooLeR** [comment]
--prefer-source
