### ISSUE TITLE
extensions.php contain dev packages in production?

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-composer#33]
Generated file "vendor\yiisoft\extensions.php" contains dev packages in production(`YII_ENV == 'prod'`). How remove they? "handmade"?

**Comment by schmunk42** [comment]
I think you need to install without dev-packages 

`composer install --no-dev`

**Comment by WinterSilence** [comment]
@schmunk42 you right, i'm stuck on update (:
