### ISSUE TITLE
Composer  1.1.0

### ISSUE THREAD

**Issue by nulledcc** [yiisoft/yii2-composer#6]
The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.

**Comment by cebe** [comment]
you have a very old version of the `yiisoft/yii2-composer` package installed. The latest version works fine with 1.1.0: https://github.com/yiisoft/yii2-composer/blob/master/composer.json#L21

**Comment by nulledcc** [comment]
Sorry for minimum information i provided ,I had updated by this version but there still error.

> The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.<

I dont know what to do else i restarted server , cleared cash but still same error

**Comment by cebe** [comment]
you can run `composer update yiisoft/yii2-composer` to get the latest version of the plugin.

**Comment by tolidano** [comment]
```
[shawn@web complimateapp]$ composer update yiisoft/yii2-composer
The "yiisoft/yii2-composer" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
```

Same result.
